Batch Export
Kitware/dive pull request #1140
Opened 2022-01-27 20:11 UTC by BryonLewis

fixes #812 

Allows for downloading of multiple datasets at a time in the WebUI without having the user go to other locations.

Two options:
- duplicate all of our existing export options (configuration, annotation, media, everything) for multiple datasets
- Or only allow full export when selecting multiple datasets?

Ideally how I think this should work from a users perspective:
- If you select multiple datasets you have the same options as before except all data will be downloaded into a single zip file instead of just downloading configuration files or oannotations.
- Behavior for selecting a single dataset should remain the same as it was before
- Selecting a non-folder dataset will git the standard `https://viame.kitware.com/api/v1/resource/download` endpoint and specify the folderId.  Might include a warning for users based on the size of the folder/subfolders.  This should create an automatic zip file which will download all of the items in that location.

Implementation for downloading multiple datasets:
Requires an additional `dive_dataset/batch_export` endpoint which will take as a parameter the list of datasetIds as well as the configuration options (`excludeBelowThreshold`,`typeFilter`) plus an additional parameter for configurations only (`configurationsOnly`).  I don't see a need for different endpoints for the batch exports?
For exporting annotations only there will need to be a separate endpoint `dive_annotation/batch_export` which will batch export the annotations.

2022-01-27 21:28 UTC, subdavis commented
> duplicate all of our existing export options (configuration, annotation, media, everything) for multiple datasets Or only allow full export when selecting multiple datasets?

full export only, IMO

> If you select multiple datasets you have the same options as before except all data will be downloaded into a single zip file instead of just downloading configuration files or oannotations.

Yep

> Behavior for selecting a single dataset should remain the same as it was before

Yes

> Selecting a non-folder dataset will git the standard https://viame.kitware.com/api/v1/resource/download endpoint

Out of scope, IMO.  We don't support this now and shouldn't add it.   The thing it would download is almost certainly not what the user wants.

> New endpoint

Yeah, just change the params of the existing one to accept an array, good call.  I don't even think you need to rename it.

2022-01-28 15:35 UTC, BryonLewis commented
I still believe that we need to have separate endpoints for exporting a single dataset vs multiple.  Mostly because I like the clarity of `GET /dive_dataset/{id}/export` and then having an additional one with less options `GET /dive_dataset/batch_export` which takes an array of folders but doesn't have the other options.

I think in implementation I would modify the `export_dataset_zipstream` to `export_datasets_zipstream` where instead of a single `girder folder` it takes an array of folders and adds them to a single zip file.

2022-01-31 17:00 UTC, subdavis requested changes
Here's another small edge case:

Batch export for clones where the source media is missing will fail in a confusing/unclear way.

Before, if you tried to export a dataset where the clone chain is broken it looked like this.

![Screenshot from 2022-01-31 11-56-22](https://user-images.githubusercontent.com/4214172/151838257-ca909607-e6c3-4c18-9136-d85b4703049e.png)

But bulk export will let you include a broken clone (expected).  I think the resulting ZIP needs to have a "failures.txt" file or the failed dataset's folder needs to have a placeholder file that says what happened  If you have a better idea, that's cool too.

2022-02-04 16:03 UTC, subdavis approved these changes
Works perfectly.

One nit to remove some dead code.

2022-02-04 16:03 UTC, subdavis commented on client/platform/web-girder/views/Home.vue
> -    },
this was the last reference of `exportTarget`, so that can be removed as well.

2022-02-04 18:18 UTC, subdavis approved these changes

2022-02-04 18:27 UTC, merged