Revision History UI
Kitware/dive pull request #1188
Opened 2022-02-28 13:24 UTC by subdavis

## Summary of changes

* Adds revision history contextual sidebar, and a button to open it which so far I really dislike.  Feedback needed.
* Clone or download annotations when a past revision is loaded.

# Menu open, Latest selected

![Screenshot from 2022-02-28 08-22-10](https://user-images.githubusercontent.com/4214172/155990492-39c3e0f0-c832-47b4-8a5c-3faf61cdec6c.png)

# Menu open, previous rev selected 

![Screenshot from 2022-02-28 08-22-23](https://user-images.githubusercontent.com/4214172/155990490-5dabaf6d-ac99-438e-9ce7-eccc6e2341ea.png)

# Download menu

![Screenshot from 2022-02-28 08-22-37](https://user-images.githubusercontent.com/4214172/155990488-e7401589-4076-449c-a479-d22409dcfc80.png)

2022-03-14 18:13 UTC, BryonLewis requested changes
This is really awesome and the ability to clone will be a nice stop-gap until true rollback is implemented.

2022-03-14 18:13 UTC, BryonLewis commented on client/dive-common/store/context.ts
> +function toggle(active: string | null) {
This use to have some Developer handy guarding based on the `ContextType` being a `keyof typeof ComponentMap` should we give this a more sane error if you use an invalid toggle?  The error isn't too bad currently but you would have to work your way back to see that you messed up the component name.  Feel free to resolve if you think this is clear enough already.
For Reference if you use an invalid component name:
![image](https://user-images.githubusercontent.com/61746913/158234330-8b87ca54-28b4-4dfb-b9d4-8a3a1a5e5030.png)

2022-03-14 18:13 UTC, BryonLewis commented on client/dive-common/use/useRequest.ts
> +    paginationParams.limit = 10;
why do you default to 20 and reset to 10?

2022-03-23 14:31 UTC, subdavis commented on client/platform/web-girder/views/RevisionHistory.vue
> +            {{ revision.revision }}: {{ revision.description }} by
I'm not sure what to do about that without committing much greater sins.

2022-03-23 20:04 UTC, subdavis commented
Switch to three line layout

![Screenshot from 2022-03-23 16-04-16](https://user-images.githubusercontent.com/4214172/159786129-f14337aa-0100-4ad8-8f23-ae872ec81d9a.png)

2022-03-23 20:14 UTC, BryonLewis approved these changes
Two super minor things that we may just want to create issues for in the future and don't need to be apart of this PR:

Don't know if this first one is really an issue?
Context View is saved in the state so if you were to back out to Data Browser with it open and load a new dataset it will start with the contextView open (either Confidence Pairs or Revision History).  I don't think this needs to be fixed.

Selecting a revision which is higher than your load limit (20) will cause it to refresh and reset the scroll page.  My fault about the `loadNext()` being activated on reload.  I have a dataset with 40 revision, I click on revision 4 and it resets all of the data and scrolling so that it isn't highlighted in the list when the revision reloads.

2022-03-24 14:51 UTC, merged