Static build of ffmpeg
Kitware/dive pull request #1250
Opened 2022-05-24 16:18 UTC by subdavis

* Add `ffmpeg` and `ffprobe` static.
* Remove platform-specific media encoders, just use `spawn` directly without shell.  Remove logic to attempt to use VIAME installation of ffmpeg.
* Remove electron devtools vue (It seems somewhat permanently broken).
* Add handler for multi-instance launch.

fixes #1245

2022-05-25 18:20 UTC, BryonLewis requested changes
I'm not nearly done with a complete review.  I just wanted to add this initially to see if we could get building for windows through the workflow going as well.  I want to take a build and put it through it's paces:

- mis-alignment checking (ffprobe) and see if it does the double transcoding
- AV1 and other weird codecs
- Removing ffmpeg from by PATH and ensuring it still works (my windows testing makes me think it should)
- Image conversion (remember we convert bmps and tifs to pngs I believe)

2022-05-26 12:23 UTC, BryonLewis requested changes
All my testing seemed to work perfectly fine.  Only one question about leaving the shell argument in the `spawnResult`.
I'm going to double check the building on Windows today to see if that works well enough.

2022-05-26 13:44 UTC, subdavis commented on client/platform/desktop/backend/native/mediaJobs.ts
> +  const result = await spawnResult(ffprobePath, false, args);
Yeah, I didn't catch that.  Thanks.  I thought viame stuff used it too.

2022-05-26 14:41 UTC, subdavis commented
@BryonLewis I think I found a simpler fix for windows.  I just added a wildcard filter to make sure the `.exe` gets bundled.  Could you test again?  Thanks.

2022-05-26 15:40 UTC, BryonLewis approved these changes
Builds on windows and I could do transcoding.

2022-05-26 16:54 UTC, merged