[WIP] Tiled images in DIVE
Kitware/dive pull request #1255
Opened 2022-06-01 19:05 UTC by BryonLewis

Working on the basics of getting tiled images running in DIVE.
I have them so they upload and can view.  I just need to reset the coordinates so that annotations properly draw in image space instead of the projections I am using to view.

2022-06-02 15:13 UTC, BryonLewis commented
TODOs:

- [ ] Figure out why poetry extras require weird importing
- [ ] Update dive_dataset/media - right now I return URLS but really only use the `id's` to hit the `/item/tile` endpoints
- [ ] Update the LargeImageAnnotator.vue so it follows closer the implementation in the girder plugin for [geojs](https://github.com/girder/large_image/blob/master/girder/girder_large_image/web_client/views/imageViewerWidget/geojs.js) and then specifically the [setFrameQuad](https://github.com/girder/large_image/blob/master/girder/girder_large_image/web_client/views/imageViewerWidget/setFrameQuad.js).  `setFrameQuad` is more used for non-geospatial imagery which is how this should be configured in the beginning.  I currnetly have it set up using a `osm` and the bounds of the tiled image to set the position.  This means that annotations are in screenspace coordinates which aren't properly transferred to geospatial.  Setting up the `setFrameQuad` should hopefully resolve this and allow visualization in pixel coordinates instead of geo.
- [ ] Figure out how pipelines will interact with nitf imagery vs pngs/videos.

2022-06-10 13:58 UTC, BryonLewis commented
Maybe a better idea is to check on the client and see if the image size, because we should have information is greater than the max_texture_size supported by the browser using 
```
var gl = document.createElement('canvas').getContext('webgl')
console.log(gl.getParameter(gl.MAX_TEXTURE_SIZE))
```
Using a variation of the above we can see that they image is greater than their display size.  So we instead decide to either kick it into Canvas mode, or generate a large image. 
So we provide a button saying that we can convert this into a large image and it hits an endpoint which converts to tiles and sets the dataset Type to 'large-image'

2022-10-25 14:24 UTC, marySalvi commented
It looks good with some minor issues:

1.  As discussed the Seatle tif crashes girder.
2. Jumping around in the image sequence can leave part of the previous image visible. Specifically from first frame to last frame.

![Screenshot from 2022-10-25 09-54-40](https://user-images.githubusercontent.com/40494088/197799818-7b873c7d-a129-4777-890c-858c4c8735fb.png)

3. There seems to be some weird UI issues in the upload dialogue.

![Screenshot from 2022-10-25 09-58-00](https://user-images.githubusercontent.com/40494088/197799931-a7c24ce6-3645-42e2-8815-07bb57217001.png)

4. Uploading the large jpgs and converting seems to work but there are 500 errors when interacting with the dataset.

![Screenshot from 2022-10-25 10-09-32](https://user-images.githubusercontent.com/40494088/197800031-858158d0-4750-48d4-8017-eeee3fb2acf2.png)

2022-10-25 14:42 UTC, marySalvi requested changes

2022-10-25 14:42 UTC, marySalvi commented on client/platform/web-girder/api/largeImage.service.ts
> +  // const { data } = await girderRest.get(`item/${itemId}/tiles?projection=EPSG%3A3857`);
This can probably be removed

2023-09-13 16:46 UTC, marySalvi approved these changes
Looks great! Maybe add that tooltip but other than that I think this is gtg

2023-09-13 16:46 UTC, marySalvi commented on client/platform/web-girder/views/Upload.vue
> +                  :name="`Add ${pendingUploads.length ? 'Another ' : ''}Tiled Images`"
Maybe add tooltip that indicates acceptable file types and that it can be a sequence too. Users might try to use the other sequence option otherwise.

2023-09-14 11:30 UTC, BryonLewis commented
I merged it with main to add in the attribute rendering and also added in the tooltip you mentioned.

2023-09-14 15:53 UTC, marySalvi approved these changes
::shipit::

2023-09-14 16:15 UTC, merged