Add TrackJSON Download and SkipTranscoding Options.
Kitware/dive pull request #1291
Opened 2022-09-09 18:06 UTC by BryonLewis

- Annotation download button modified within web version to have a dropdown to select the TrackJSON instead of always exporting the viame-csv format
- Logic included preventing transcoding when uploaded with the `skipTranscoding` parameter set to true.  Should only be done by those who know that their video is h264 encoded.

2022-09-12 13:45 UTC, BryonLewis commented
> > * Logic included preventing transcoding when uploaded with the `skipTranscoding` parameter set to true.  Should only be done by those who know that their video is h264 encoded.
> 
> What happens if you knowingly enable this option on a video that's _not_ in the right format? (i.e., what kind of error message or error state will the user find themselves in?)

Currently, it will fall back on transcoding the video.  That is probably not desired when importing videos and having that option set.  I can easily change it to create an error in the job log.

2022-09-12 14:02 UTC, BryonLewis commented
Note to self:  Clarify the setting as being "Attempt to Skip transcoding".  It will fall back to transcoding if the video files are not in the proper format.  Log this information in the Job log and update the UI elements to accurately indicate to the user this setting (may need to use a help icon tip for the longer explanation).

2022-09-20 19:08 UTC, marySalvi requested changes
Looks great, working well. Just minor grammar changes.

2022-09-20 19:08 UTC, marySalvi commented on server/dive_tasks/tasks.py
> +
```suggestion
            print('Transcoding cannot be skipped:')
            print(f'Codec Name: {videostream[0]["codec_name"]}')
            print('Codec name is not h264 so file will be transcoded')

```

2022-09-20 19:08 UTC, marySalvi commented on client/platform/web-girder/views/Upload.vue
> +                  '.mp4' and encoding using the h264 codec.
```suggestion
                  '.mp4' and encoded using the h264 codec.
```

2022-09-21 12:51 UTC, marySalvi approved these changes

2022-09-27 14:05 UTC, marySalvi approved these changes

2022-09-27 14:18 UTC, merged