Additive import
Kitware/dive pull request #1309
Opened 2022-11-23 16:17 UTC by BryonLewis

This is a PR that was an upstream branch for some other deployments.  For right now these changes are in the Web Version only.  I can make a separate PR to incorporate these changes into the electron version.

Creates an additive import option for `postprocess`:
`additive` means that if an annotation file is found during postprocess it will add the tracks to existing tracks instead of doing a replacement.
`additive_prepend` is a value that is prepended to all types of the new tracks found.  This is to easily filter the tracks in the type editor between the new and old tracks.

Code Changes:

- Post process has additional flags 'additive' to indicate that the import should be additive to the current tracks. 
- 'additivePrepend' is a prepended type that should be added to all tracks imported using additive.  I.E, if you have existing tracks named fish and the import has more tracks named fish, if you use an additivePrepend of 'newer' then all of the new annotations will be renamed to 'newer_fish' for their type.
- There are some UI changes to support this additive prepend functionality.  Mostly allowing from the interface to check off an import as being additive and providing a Prepend name value.
- Fix for transcoding so that videos that contain multiple video streams it will use the first videostream
- Custom sorting for annotations.  Annotations in CSV files were occasionally given in the wrong frame order.  This attempts to fix that order by custom sorting the CSV rows in python.

I apologize for the commit history, if required I can squash it down.  During the merge it will become squashed anyways.

2023-05-04 16:50 UTC, marySalvi requested changes

2023-05-04 16:50 UTC, marySalvi commented on client/dive-common/components/ImportAnnotations.vue
> +            </div>
Perhaps a tooltip or hint to explain the functionality of this prepend text

2023-05-04 16:50 UTC, marySalvi commented on client/dive-common/components/ImportAnnotations.vue
> +              />
I feel like `additive` isn't intuitive. Perhaps instead a checkbox with an 'overwrite' label defaulted to checked.

2023-05-04 16:50 UTC, marySalvi commented on client/platform/desktop/backend/native/common.ts
> +  cloneDeep, merge, uniq, pick, add, max,
looks like `add` and `max` isn't used

2023-05-05 19:34 UTC, BryonLewis commented
I am completely open to any other wording or suggestions that you may have for it.  I also looked through the code and it looks like I already implemented the Desktop version of this (It's been a branch for too long and I forgot :facepalm: )

2023-05-05 20:17 UTC, marySalvi commented
> I also looked through the code and it looks like I already implemented the Desktop version of this (It's been a branch for too long and I forgot  )

Heh I noticed that but I thought maybe it wasn't fully hooked up yet. I'll do a visual check on desktop, already checked the code.

2023-05-05 21:01 UTC, marySalvi approved these changes

2023-05-08 11:59 UTC, merged