Add docs about pipeline upload, add Advanced Features subsection
Kitware/dive pull request #659
Opened 2021-03-22 18:55 UTC by subdavis

Add docs about pipeline upload.

Hide CLI, Server Operator, and Pipeline Upload under an "Advanced Features" heading to dissuade casual readers from confusing these pages for real user guide pages.

fixes #651

2021-03-23 12:48 UTC, subdavis commented
Turns out we also need to support requiring input detections for these user-uploaded pipelines.  I think some simple metadata would work for this in lieu of the full schema thing being ready (or even as a permanent fallback, Idk).

2021-03-24 17:06 UTC, subdavis commented
Turns out multi-directory includes were supported all along: https://github.com/VIAME/VIAME/issues/131

We could have been pulling addons into some separate directory without having to copy over the `common_*` pipes.  I might see if I can clean this up.

2021-03-24 18:01 UTC, subdavis commented
This PR now has some additional changes that allow user upload of any `.pipe` file.

* It is no longer necessary to rename the file `detector.pipe`
* The truthiness check for `trained_pipeline` is looser now.
* The pipe can safely `include` from common or addon pipelins
* The pipeline can specify that it takes input with `requires_input` truthy check.

I have specifically tested and you can upload just the `utility_add_segmentations_watershed.pipe` and tag it properly and it runs.

2021-03-24 19:22 UTC, BryonLewis requested changes
Minor docs edits and some questions about mixing user and `utility` pipes that require input.

Ran it through most everything I could think that was touched.  Created tracks with the default utilities, and uploaded ones, did training, imported default pipelines and imported custom trained ones from desktop as well.

2021-03-24 19:22 UTC, BryonLewis commented on docs/Pipeline-Upload.md
> +    1. Whatever other model `.zip` files are required by the pipe, named exactly as the appear in your `.pipe` file above.
I think you want it named as it `they appear inside your` 
typically this is `trained_detector.zip` or something like that for trained detectors.

2021-03-24 19:37 UTC, subdavis commented on docs/Pipeline-Upload.md
> +User-uploaded pipelines may `include` any pipe already installed from the base image or an addon. Including other user-uploaded pipes is not supported.
This is referring to the `include` keyword in pipe files.  You cannot upload or use a pipe file that depends on another pipe file that was also uploaded.

2021-03-24 19:39 UTC, BryonLewis commented on docs/Pipeline-Upload.md
> +User-uploaded pipelines may `include` any pipe already installed from the base image or an addon. Including other user-uploaded pipes is not supported.
ahh I didn't realize `include` was inside the context of a .pipe.

2021-03-24 19:49 UTC, russelldj commented on docs/Pipeline-Upload.md
> +User-uploaded pipelines may `include` any pipe already installed from the base image or an addon. Including other user-uploaded pipes is not supported.
I'm not sure if this is at all useful in this context but `kwiver pipe-config -o` allows you to export a pipeline with all the content from `include`d files in one file. Perhaps documenting this is a good stopgap before supporting includes on the user side.

2021-03-24 19:59 UTC, subdavis commented on docs/Pipeline-Upload.md
> +User-uploaded pipelines may `include` any pipe already installed from the base image or an addon. Including other user-uploaded pipes is not supported.
@russeldj thanks I added a reference to this.  However, with this change, we will also support `includes` except in a very niche case.

2021-03-24 20:19 UTC, BryonLewis approved these changes

2021-03-24 20:39 UTC, merged