Summarize published data
Kitware/dive pull request #668
Opened 2021-03-26 14:14 UTC by subdavis

fixes #540 
fixes #648

2021-03-26 20:23 UTC, BryonLewis requested changes
Overall it works very well.  Just a few questions/comments.  I think depending on the opt-in/opt-out discussion for users if it becomes opt-in we may want to make it easier for them to tag their public data using a context menu in GWC or something else on the folder.

2021-03-26 20:28 UTC, subdavis commented on server/dive_server/constants.py
> +PublishedMarker = 'published'
Yes, thank you.

2021-03-26 20:30 UTC, subdavis commented on server/dive_utils/models.py
> +    found_in: List[str]
There's insufficient horizontal space to use anything but a short segment of the ID IMO.

We could include the name, but there's nowhere on the page to put it.

2021-03-26 20:31 UTC, subdavis commented on client/platform/web-girder/views/Summary.vue
> +                v-for="datasetId in item.found_in"
That was as far as my plan went for now.

2021-03-26 20:32 UTC, BryonLewis commented on client/platform/web-girder/views/Summary.vue
> +                v-for="datasetId in item.found_in"
yeah that is completely fine.  We can deal with it if it becomes an actual problem.

2021-03-26 20:33 UTC, subdavis commented on client/package.json
> +    "color-hash": "^1.0.3",
As far as I can tell, that's a finite number of colors.  I need MOAR.  Is there a d3 option more similar to color hash?

2021-03-26 20:39 UTC, BryonLewis commented on client/package.json
> +    "color-hash": "^1.0.3",
yeah I think you have to sort of build it by using a color scale range as the input for the scale ordinal.  You then have an issue where you could possible get similar colors based on how it does the hashing.  color-hash just works so I think it's easier to use that.  There is some upper limit where eventually the colors aren't different enough.

2021-03-27 11:58 UTC, BryonLewis approved these changes

2021-03-27 13:17 UTC, merged