Refactor prompt-service to use composition-api
Kitware/dive pull request #804
Opened 2021-06-10 18:06 UTC by f4str

fixes #664 

The files `client/dive-common/vue-utilities/prompt-service/Prompt.vue` and `client/dive-common/vue-utilities/prompt-service/index.ts` are both rewritten using composition-api and typescript.

Instead of using `root.$prompt({...}` to call the prompt box, instead import the prompt provider
```typescript
import { usePrompt } from 'dive-common/vue-utilities/prompt-service'
```
Call the prompt box by getting the `PromptService` class and calling the show function
```typescript
const prompt = usePrompt();
prompt.show({...});
```
This will be updated in the README.md later

2021-06-10 18:10 UTC, f4str commented on client/dive-common/vue-utilities/prompt-service/index.ts
> +    Vue.extend({ vuetify, ...Prompt });
There are issue with this line. This currently does not properly inject vuetify into `Prompt.vue` and the colors of the prompt box are incorrect. The code in the original javascript file was
```typescript
Prompt.vuetify = vuetify
```
However, this is not valid in typescript and does not compile. Needs further investigation on a fix.

2021-06-16 18:24 UTC, subdavis requested changes
@f4str I made a couple changes here to address the vuetify issue and simplify the "resolve" logic.

Please LMK if this looks good to you and we can merge.

2021-06-16 19:21 UTC, f4str commented
@subdavis everything looks good to me. Seems to work on both web and desktop as far as I can see. I also updated the README to remove the redundant statement.

2021-06-16 19:55 UTC, subdavis approved these changes

2021-06-16 20:14 UTC, merged