Feature 190
Kitware/dive pull request #891
Opened 2021-08-15 18:57 UTC by BryonLewis

Fixes #190 

- Adds into the user Settings a prompt setting for prompting the user when deleting objects.
- Restructured `NewTrackSettings` into having `TrackSettings` with a new `DeletionSettings`.  It is one value for now but I don't know if more will be added in the future.
- The localStorage uses the same format just with an additional field.
- Updated the `useModeManager` `handleRemoveTrack` to prompt if the user settings indicate so.  There is an option override which is used for  track visibility deletion tool (The delete button next to track settings).

![Selection_265](https://user-images.githubusercontent.com/61746913/129489351-71d9c0fb-79eb-460e-bd52-337bfcf4faca.png)

Left To do:

- [ ] Some more testing to make sure there was not interference or problems with the new updates.
- [ ] Just need to check with fresh eyes to make sure I didn't do anything to bad in this mode.

2021-09-03 16:59 UTC, subdavis requested changes
We should be vigilant about naming and avoid proliferation of symbols with names that 1) don't really describe the entity and 2) are very close to other things.  There's a similar problem in `common.ts` in desktop.

Stuff like this really impacts readability because rather than relying on intuition, you have to rely on bulk memorization to know what things do.

Please hold me accountable to this as well.

Rather than introduce 2 more symbols to the `useSettings` namespace, could we just rename `NewTrackSettings` to `TrackSettings` add `promptUserOnDelete` to `TrackSettings`.

Putting `DeletionSettings` into its own namespace doesn't make sense, because if we end up with settings that affect other types of deletions (users, types, etc) then we can't put them in DeletionSettings because it's a child of `TrackSettings`.

Then, `updateNewTrackSettings` should move to simply `updateTrackSettings`.

I'd actually prefer to do away from putting settings into these arbitrary groups at all and have a `AnnotatorSettings` interface and a `updateSettings()` function and never have to add new symbols to the useSettings api, but this could be out of scope for this PR.

2021-09-03 17:16 UTC, BryonLewis commented
> I'd actually prefer to do away from putting settings into these arbitrary groups at all and have a `AnnotatorSettings` interface and a `updateSettings()` function and never have to add new symbols to the useSettings api, but this could be out of scope for this PR.

Understood and I wasn't a fan either considering my last bulletpoint. I'll swap it, I was just avoiding doing an update to users who currently had data in localStorage stored a top level newTrackSettings

2021-09-03 18:05 UTC, subdavis commented
>  I was just avoiding doing an update to users who currently had data in localStorage stored a top level newTrackSettings

On the balance, maybe don't bother?  Just change the name of the variable and let users's settings be overwritten with the defaults.   It's just a couple toggle switches.  I don't think I'd bother attempting to migrate them.

2021-09-03 20:45 UTC, BryonLewis commented
I need to do some double checking of stuff, and I think refactoring some of the components to composition and using `toRef` so I can maintain reactivity and not have these long property chains.

2021-09-04 18:30 UTC, BryonLewis commented
Okay I think I have this working like it should.  a `reactive` AnnotationSettings object is passed around and depending on where it is used the sub-settings are converted to a ref using `toRef` so they maintain their reactivity and can be used in vue templates while destructuring the property.
This keeps everything using the type of `AnnotationSettings` and the toRef will maintain the proper type with the wrapper of a `Ref<SubSettingsType` so it can be properly used.

2021-09-07 20:11 UTC, subdavis requested changes
LGTM, one nit.

2021-09-07 20:15 UTC, BryonLewis commented on client/dive-common/use/useModeManager.ts
> +  async function handleRemoveTrack(trackIds: TrackId[], promptOverride = false) {
are you good with `forcePromptDisable`?   just so know what you're force disabling.

2021-09-07 20:17 UTC, subdavis commented on client/dive-common/use/useModeManager.ts
> +  async function handleRemoveTrack(trackIds: TrackId[], promptOverride = false) {
Yep sounds good.

2021-09-08 02:37 UTC, subdavis approved these changes

2021-09-08 11:54 UTC, merged