Fix 905
Kitware/dive pull request #912
Opened 2021-08-31 18:55 UTC by subdavis

It's all a bunch of indentation changes, but git aligned them badly, so it looks like a huge diff.

fixes #905

2021-09-01 13:23 UTC, subdavis commented
* refactor popen into `stream_subprocess`
* context managers only
* context manager for `suppress(CanceledError)` instead of try/except
* `utils.make_directory` instead of having to remember to `mkdir` for new folders.

2021-09-01 21:19 UTC, BryonLewis requested changes
Everything seems to work, (import, transcoding, frame alignment, image transcoding, running pipelines, running utility pipelines).  I didn't directly test training yet.

Just some questions about arguments been passed in and if we want to use Path instead of strings.  I think we are fine using `PosixPath` items considering it's all linux, but would probably most likely have consistency.

2021-09-01 21:19 UTC, BryonLewis commented on server/dive_tasks/frame_alignment.py
> +        aligned_file,
Depending on the above comment this is really a `Path` being passed into the ffmpeg argument.

2021-09-01 21:37 UTC, subdavis commented on server/dive_tasks/tasks.py
> +        output_file_path = _working_directory_path / f"{item['name']}.transcoded.mp4"
yes.  I didn't really see a reason to go to all the trouble to slice out the old extension name.  This new name is more informative than `tmppq28urifja.mp4`

2021-09-01 21:38 UTC, subdavis commented on server/dive_tasks/frame_alignment.py
> +    aligned_file = file_path.parent / f"{file_path.name}.aligned.mp4"
Same, didn't seem like it was worth the effort to change.

I'll change the variable name.

2021-09-01 22:44 UTC, subdavis commented on server/dive_tasks/tasks.py
> +            command = ["ffmpeg", "-i", item_path, new_item_path]
The part I think you read only matters if `args` is a `Path`, but here, args is an array of strings and path-likes.

That's handled by `list2cmdline`, and particularly by `os.fsdecode`

https://github.com/python/cpython/blob/e09dd8aafd6f9aef03945c417267806d47084a5d/Lib/subprocess.py#L565
https://docs.python.org/3/library/os.html#os.fsdecode

> Also need to make sure we never join a sequence containing mixes of strings and paths, I don't think that would go well.

We don't, but I think this is actually a good argument to convert it ourselves.  If we ever swap to `shell: True` then we'd have to join the args and get an error.  

I'll change these to strings.

2021-09-01 22:48 UTC, subdavis commented on server/dive_tasks/tasks.py
> +            command = ["ffmpeg", "-i", item_path, new_item_path]
And yes, I did mean to pass a non-string.  If shell is true, you need a string, otherwise, it's preferable to pass a list.

2021-09-02 12:04 UTC, BryonLewis approved these changes
Did testing again this morning and it looks good.  Thanks for the `Popen` info.

2021-09-02 12:09 UTC, merged