Docs/deployment updates
Kitware/dive pull request #923
Opened 2021-09-09 14:08 UTC by subdavis

Significant rewrite of the deployment docs, live now at https://kitware.github.io/dive/Deployment-Overview/

* https://kitware.github.io/dive/Deployment-Overview/ describes every existing deployment option
* https://kitware.github.io/dive/Deployment-Provision/ describes VM provisioning for each option
* `docker/README.md` has moved to https://kitware.github.io/dive/Deployment-Docker-Compose/ and was updated tobe more friendly for end users
* https://kitware.github.io/dive/Deployment-Storage/ was moved to a separate page so it isn't confused as instructions for regular deployement.
* `README.md` was updated with pointers to new docs.
* https://kitware.github.io/dive/Command-Line-Tools/ is now docs for the python CLI, and the Node CLI will not be mentioned in user-facing docs.

2021-09-09 15:10 UTC, BryonLewis requested changes
Mostly comments that can be ignored if it is too much trouble to implement.  just two word miss-types are the real request.

2021-09-09 15:10 UTC, BryonLewis commented on docs/Command-Line-Tools.md
>  > **NOTE** this is an experimental feature with an unstable API.
may want to clearly note that DIVE CLI is different than VIAME CLI?

2021-09-09 17:08 UTC, subdavis commented on docs/Deployment-Overview.md
> +
I sorta like it where it is

2021-09-09 17:09 UTC, subdavis commented on docs/Deployment-Overview.md
> +## Our server vs running your own
Yeah, I think we probably want to deemphasize this option and also space limitations.

2021-09-09 18:53 UTC, subdavis commented on docs/Deployment-Docker-Compose.md
> +After initial deployment, a DIVE server will only have basic VIAME pipelines available. VIAME optional patches are installed and upgraded using a celery task that must be triggered by hand. Run this
Updated because it's out of date, but I wanted this to visually match the thing you see on the swagger page.  I updated the swagger link instead.

2021-09-09 19:06 UTC, subdavis commented on docs/Deployment-Docker-Compose.md
> +nano .env
Added a comment here and several updates in the actual template.

2021-09-09 19:07 UTC, subdavis commented on docs/Deployment-Provision.md
> +
Added inline in the table and command comments.

2021-09-09 21:24 UTC, BryonLewis submitted a review, later dismissed

2021-09-10 14:13 UTC, BryonLewis approved these changes

2021-09-10 14:15 UTC, merged